/*
 * Copyright (c) Mike Brickman 2014-2017
 */

package org.egility.android.tools

import org.egility.library.general.debug

/**
 * Created by mbrickman on 07/06/15.
 */

enum class SignalCode {
    UNDEFINED,
    PANIC,
    PAGE_UP,
    PAGE_DOWN,
    RESET,
    RESET_FRAGMENT,
    CLEAR_DATA,
    BACK,
    FINISHED,
    EXIT,
    OK,
    DO_NOTHING,
    KEYBOARD_ENTER,
    PREVIOUS,
    NEXT,
    CANCEL,
    PULSE,
    LOOKUP,
    MEMBER_HEIGHT_SELECTED,
    HEIGHT_SELECTED,
    HEIGHT_CHANGED,
    SELECT_LIST,
    CONNECT_NEAREST, SCAN_ACUS, ACUS_FOUND, CONNECT_ACU, 
    CONNECT_TO_DATABASE,
    HAVE_WIFI_CONNECTION, WIFI_CONNECTING,
    HAVE_DATABASE_HOST, UPDATE_APP,
    BACKGROUND_EXCEPTION,
    LATE_ENTRY,
    CONFIRM_ENTRY,
    UNCONFIRM_ENTRY,
    JOIN_QUEUE,
    LEAVE_QUEUE, LEAVE_QUEUE_QUESTION,
    JUMP_QUEUE, JUMP_QUEUE_SELECTED, MOVE_IN_FRONT_OF,
    WITHDRAWN,
    UN_WITHDRAWN,
    REMOVE_ENTRY,
    UN_REMOVE_ENTRY,
    CHANGE_ENTRY_HEIGHT,
    NEGATE,
    LOOKUP_TEAM,
    LOOKUP_TEAM_BY_NAME,
    LOOKUP_TEAM_LIST,
    EDIT_SCORE,
    ENTER_SCORE,
    RE_RUN_TIME,
    RE_RUN_SCRATCH,
    WIPE_SCORE,
    RE_RUN_TIME_QUESTION,
    RE_RUN_SCRATCH_QUESTION,
    WIPE_SCORE_QUESTION,
    ENTER_TIME,
    WAIT_FINISH,
    RUN_COMPLETE,
    DIGIT,
    CHAR,
    DELETE,
    DELETE_ALL,
    HANDLER_CODE_UPDATED,
    DOG_CODE_UPDATED,
    HAVE_ENTRY,
    MEMBER_SELECTED,
    HAVE_TEAM_ID,
    ENTRY_SELECTED,
    SCORE_CODE,
    SCORE_CHANGED,
    CLOSE_CLASS,
    DO_CLOSE_CLASS,
    CHECK_CLOSE_CLASS,
    CLASS_CLOSED,
    FORCE_CLOSE_CLASS,
    TIME_CODE,
    UPDATE_STATUS,
    UPDATE_SOFTWARE,
    PIN_UPDATED,
    LEVEL,
    SEQUENCE,
    RING_DETAILS,
    REQUEST_CHECKOUT,
    CHECKOUT,
    CHECKOUT_FREE,
    PAYMENT_RECEIVED,
    ALREADY_PAID,
    EDIT_RING_DETAILS,
    CLEAR_NOTE,
    CLASS_SELECTED,
    ADJUST_TIME,
    RESET_CLOCK,
    VIEW_RESULTS,
    VIEW_MISSING,
    VIEW_CHECK_IN,
    SELECT_RESULTS_HEIGHT, SELECT_RESULTS_SUB_CLASS,
    RE_PRINT_RESULTS, RE_PRINT_AWARDS,
    DISPLAY_RESULTS,
    PRINT_LATE_ENTRIES,
    PRINT_COMPLIMENTARY_ENTRIES,
    PRINT_COMPLIMENTARY_USED,
    PRINT_SPECIAL_ENTRIES,
    PRINT_CHEQUES_LIST,
    PRINT_ACCOUNT_PAYMENTS,
    PAID_CREDITS,
    PAID_CASH,
    PAID_CHEQUE,
    PAID_CHEQUE_IN_POST,
    BALANCE_CASH,
    BALANCE_CHEQUE,
    REOPEN_CLASS,
    BUY_LATE_ENTRY,
    COMPLIMENTARY_ENTRY,
    ADD_TEAM,
    MEMBER_MENU,
    STAFF_CREDIT,
    REP_CREDIT,
    DISCRETIONARY_CREDIT,
    GRADE_SELECTED,
    GRADE_SELECTED_PERFORMANCE,
    GRADE_SELECTED_STEEPLECHASE,
    DOG_MENU,
    DOG_REGISTER, DOG_REGISTER_CHECKOUT,
    MEMBER_REGISTER, MEMBER_REGISTER_CHECKOUT,
    SHOW_STATS,
    PROGRAMME_SELECTED,
    REQUEST_CHANGE_ENTRY_HEIGHT,
    PROPOSED_RING,
    NEW_RING_ORDER,
    SELECT_MENU,
    START_ACTIVITY,
    ENTRY_OPTIONS,
    CANCEL_RUN,
    CANCEL_EDIT,
    ACCEPT_EDIT,
    SWAP_DOG, SWAP_DOG_CONFIRM, SWAP_DOG_SELECTED, CRASH, REFRESH,
    DEVICE_RING_PARTY, DEVICE_SCOREBOARD, DEVICE_SECRETARY, DEVICE_SYSTEM_MANAGER, RING_SELECTED, SELECT_RING, CHECK_PIN,
    UPDATE_SCREEN, TOGGLE_LOCK, PAY_BALANCE, CHEQUE_IN_POST, DIFFERENT_AMOUNT, SET_PAYMENT, PAY_NOW, CONTINUE_SHOPPING,
    SELECT, MENU_QUERY_PROGRESS, MENU_QUERY_SCRIME, ADJUST_ZERO, CANCEL_ON_ACCOUNT, RETURN_CHEQUE, CANCEL_RETURN_CHEQUE, CREDITS_USED, TRANSACTIONS,
    CHECKOUT_EDIT, CHANGE_TO_CASH, CHANGE_TO_CHEQUE, CHANGE_TO_IN_POST, SET_PROGRESS, WALKING_OVER_LUNCH, START_TIME_CHANGED,
    MOVE_TO_ANOTHER_RING, MOVE_TO_RING, MANAGE_COMBINED_CLASS, START_ACTION, SELECT_HEIGHT, REQUEST_LOCKED_FOR_ENTRIES, REQUEST_LOCK_FOR_ENTRIES,
    LOCKED_FOR_ENTRIES, UN_LOCK_FOR_ENTRIES,
    PRINT_RUNNING_ORDERS, EDIT_RUNNING_ORDERS, REGENERATE_RUNNING_ORDERS, DO_MENU, ALTERNATIVE_HANDLER, TEAM_NAME_ENTERED, SELECT_TEAM, EDIT_TEAM_NAME, DOG_SELECTED,
    SELECT_MEMBER_USING_CODE, SELECT_DOG_USING_CODE, UPDATE_MEMBER, SPECIAL_CLASS_HANDLER, DOG_COMPETITOR_SELECTED,
    SPECIAL_CLASS_HANDLER_CHANGE, OBSTACLES, CANCEL_WAIT, RESULTS_OK, REGISTER_MEMBER, REGISTER_DOG, DEVICE_SETUP,
    TRANSFER_ENTRY, SWAP_PAIR, EDIT_ENTRY, NETWORK_PROGRESS, TEAM_MEMBER_HEIGHT_SELECTED, TEAM_MEMBER_SELECTED,
    PAIRS_ORDER_WRONG, PAIRS_ORDER_CORRECT,
    SHOW_ENTRY_OPTIONS,TEAM_LOOKED_UP, PRINT_ENTRIES,

    ENTER_SPECIAL_CLASS, LOAD_MENU_ACTIVITY, SCRIME_QUEUE, SCRIME_RUN, SCRIME_NOT_RUN, SCRIME_OTHER, SCRIME_NO_RUNNER, SCRIME_FINISH, ENTER_RELAY_EVENT, ABANDON_RELAY_EVENT,
    REVIEW_NAME, REVIEW_HEIGHTS, REVIEW_HEIGHT, REVIEW_MEMBER, KILL_SYSTEM, KILL_AUTHORIZED, KILL_CONFIRMED, BATTERY, MEMBER_EXISTS,
    HAVE_MEMBER_CODE, HAVE_HANDLER,
    CONTROL_UNIT_MENU, CONTROL_UNITS_SCAN, CONTROL_UNIT_DEBUG,
    UNIT_POWER_OFF, UNIT_REBOOT, UNIT_RESET_DATABASE, UNIT_RESET_SERVICES, UNIT_MAKE_MASTER,
    END_OF_DAY_CASH_DONE, END_OF_DAY_SUMMARY_BACK, END_OF_DAY_CHEQUE_BACK, END_OF_DAY_CHEQUE_DONE, END_OF_DAY_ACCEPT,
    END_OF_DAY_PRINT, ACCOUNTING_DAY_SELECTED, CASH_REMOVED, ACU_OPTION,
    SELECT_DAY, CALL_TO, CHANGE_HANDLER, CHANGE_HANDLER_TO_NAME, CHANGE_HANDLER_TO_ID_TEAM, CHANGE_HANDLER_OTHER, CHANGE_HANDLER_TO_ID_COMPETITOR, 
    CHANGE_GRADE, CHANGE_HEIGHT, GRADE_CHANGED, GRADE_TYPE_CHANGED, HEIGHT_TYPE_CHANGED, CHANGE_JUMP_HEIGHT, CHANGE_DIVISION, JUMP_HEIGHT_CHANGED, REVIEW_CLASSES,
    SET_SYSTEM_DATE, CHANGE_CLASS_ORDER, LIST_BY_NAME, RUNNERS_LIST, POPUP, HANDLER_CHANGED, TOGGLE_PARENT_MODE, SWITCH_SHOW, TOGGLE_CONTROL,
    PRINT_CALLING_SHEETS, PRINT_SCRIME_SHEETS, PA_CATAGORY_SELECTED, PA_CONFIRM, PA_HAVE_AT_TIME, PA_HAVE_LUNCH_TIME, PA_HAVE_RESUME_TIME, PA_CALLING_TO, PA_WALKING, 
    PA_LUNCH, PA_LUNCH_CLOSED, PA_LUNCH_NOT_BREAKINGD, 
    PA_STARTING_AT, PA_RESUMING_AT, PA_LUNCH_STARTING_AT, PA_HAVE_MINUTES, PA_LUNCH_HAVE_MINUTES, PA_HAVE_CALL_TO, CLOSING_HEIGHT_SELECTED,
    VIRTUAL_RADIO, RADIO_LOCK, IMPORT_ACCOUNT, UKA_MEMBERSHIP, UKA_MEASURE, 
    EXIT_MENU, REASSIGN_TABLET, UNASSIGN_TABLET, UPDATE_TABLET, UPDATE_TABLET_SD, TABLET_SETTINGS, BACKLIGHT_ON, BACKLIGHT_OFF, TABLET_RELOAD, ACU_WPS,
    GROUP_SELECTED, GROUP_CHANGED, LOCK_ENTRIES, UNLOCK_ENTRIES, PAPER_SCRIME, PAPER_SELECTED,
    TEST

}

class Signal(val target: SignalListener, val signalCode: SignalCode, val _payload: Any? = null, val _payload2: Any? = null) : Runnable {

    var isConsumed: Boolean = false
        private set

    override fun run() {
        if (signalCode != SignalCode.PULSE) {
            debug("Signal", "do %s.%s", target.javaClass.simpleName, signalCode.toString())
        }
        isConsumed = false
        target.onSignal(this)
    }

    fun consumed() {
        isConsumed = true
    }


}




